# Site
repository: gardenlee21/
# favicon: images/favicon.ico

# Content configuration version
version: 3

# Personal info
name: Jeongwon Lee
title: Junior AI researcher
email: gardenlee21@kaist.ac.kr
# website: www.github.com/gardenlee21/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  gardenlee21
linkedin_username: gardenlee21
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: google-scholar
  icon: fa fa-graduation-cap
  url: https://scholar.google.co.kr/citations?hl=ko&user=2UHA0xYAAAAJ

additional_links:
- title: cv
  icon: fa-solid fa-memo
  url: https://scholar.google.co.kr/citations?hl=ko&user=2UHA0xYAAAAJ

# About Section
about_title: About Me
about_profile_image: images/20220221_이정원.jpg
about_content: | # this will include new lines to allow paragraphs
 I am a Master student at the [Brain Reverse Engineering and Imaging Lab](http://brain.kaist.ac.kr/brain/main.php) of KAIST EE (advisor: Dae-shik Kim). 
 My research area is medical imaging and deep learning.
 I received my B.S. in Electrical Engineering (minor: Physics) from KAIST in February 2022.
 
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
